"""'change_type_cteater_id'

Revision ID: 2d5372b6bdcb
Revises: 39e82b6a29a2
Create Date: 2024-11-16 14:28:37.156629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5372b6bdcb'
down_revision: Union[str, None] = '39e82b6a29a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('creater_id', sa.Integer(), nullable=False))
    op.drop_column('rooms', 'creater')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('creater', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'creater_id')
    # ### end Alembic commands ###
