"""change name_of_room unique=True

Revision ID: ef55fee02303
Revises: fc769c74f426
Create Date: 2024-11-16 15:03:25.382370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef55fee02303'
down_revision: Union[str, None] = 'fc769c74f426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rooms', ['name_of_room'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    # ### end Alembic commands ###
