"""add colum limited

Revision ID: fc769c74f426
Revises: 2d5372b6bdcb
Create Date: 2024-11-16 14:45:41.848284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc769c74f426'
down_revision: Union[str, None] = '2d5372b6bdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('limited', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'limited')
    # ### end Alembic commands ###
